server.port: 9999

spring:
  kafka:
    bootstrap-servers: kafka:9092

spring.temporal:
  host: temporaltest-frontend
#  host: localhost
  port: 7233
  useSsl: false
  createWorkers: true
  namespace: billing
  workflowDefaults:
    executiontimeout: 1000
    executiontimeoutUnit: SECONDS
    activityPoolSize: 100
    workflowPoolSize: 50
  workflows:
    PostOperation:
      taskQueue: PostOperation