server.port: 9999

spring.temporal:
  host: temporaltest-frontend
  port: 7233
  useSsl: false
  createWorkers: true
  namespace: billing
  workflowDefaults:
    executiontimeout: 1000
    executiontimeoutUnit: SECONDS
    activityPoolSize: 100
    workflowPoolSize: 50
  workflows:
    PostOperation:
      taskQueue: PostOperation